#!/bin/bash
source ~/.larapath

if [[ $LARAPATH_DIR = "" ]]
then

echo "Please type the full path of your Laravel app (where you can find your .env of your Laravel project)\n\n"
echo "Example: ~HOME/desktop/myLaravelApp\n\n"
read larapath_prompt
echo "export LARAPATH_DIR=$larapath_prompt " > ~/.larapath

else
if [[ $1 = '--controllers' ]] || [[ $1 = '-ct' ]]
then

cd $LARAPATH_DIR/app/http/controllers


elif [[ $1 = '--root' ]] || [[ $1 = '-r' ]]
then

cd $LARAPATH_DIR

elif [[ $1 = '--views' ]] || [[ $1 = '-vw' ]]
then

cd $LARAPATH_DIR/resources/views

elif [[ $1 = '--routes' ]] || [[ $1 = '-rt' ]]
then

cd $LARAPATH_DIR/routes

elif [[ $1 = '--path' ]] || [[ $1 = '-p' ]]
then

echo -n "Please type the full path of your Laravel app (where you can find your .env of your Laravel project)"
echo -n "Example: ~HOME/desktop/myLaravelApp"
echo ""
read -r larapath_prompt
echo "export LARAPATH_DIR=$larapath_prompt " > ~/.larapath


elif [[ $1 = '--help' ]] || [[ $1 = '-h' ]]
then

echo ""
echo "LaraPath tools - Fast CLI access to Laravel folder"
echo "Author: Antoine Rondeau - https://softob.ca"
echo "Current project path:" $LARAPATH_DIR
echo ""
echo "--root            -r        Access to root project folder"
echo "--controllers     -ct       Access to Controllers folder"
echo "--views           -vw       Access to Views folder"
echo "--routes          -rt       Access to Routes folder"
echo "--path            -p        Change LaraPath Laravel folder"

else 
echo "You need an option (-h for help)"
fi
fi
